"""fix dots

Revision ID: 8ba829dbcebe
Revises: 55c3884592f4
Create Date: 2024-04-13 00:04:35.624001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba829dbcebe'
down_revision: Union[str, None] = '55c3884592f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dots', 'ids')
    op.drop_column('dots', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dots', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('dots', sa.Column('ids', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
